### ISSUE TITLE
Solicitud para equipo de piezas.

### ISSUE THREAD

**Issue by Drazen420** [norman-ipn/Ajedrez2016#19]
Necesitamos que suban las funciones de verificar movimiento de las demás piezas para poder validar jaque y jaque mate

**Comment by norman-ipn** [comment]
Es necesario Asignar a tus compañeros a este issue para que estén enterados, del lado derecho puedes realizar las asignaciones y en el README.md puedes consultar sus nombre de usuario y el módulo asignado
