### ISSUE TITLE
Solicitud para retirar menu de main.c

### ISSUE THREAD

**Issue by alex2201** [norman-ipn/Ajedrez2016#20]
Hola, yo soy del módulo de interfaz y revisando el archivo menu.c me di cuenta que hay una especie de menu dentro de la función. Esta es una solicitud para perdir que lo retiren y hagan referencia a nuestra función de menú puesto que en el archivo interfaz.c ya se creó un menú.

**Comment by norman-ipn** [comment]
Hola Alex2201, este issue tiene que ser asignado a alguno de los compañeros del módulo correspondiente y ellos lo deben de cerrar cuando lo terminen.
