### ISSUE TITLE
Movimiento de piezas graficamente

### ISSUE THREAD

**Issue by OscarGPDev** [norman-ipn/Ajedrez2016#23]
Con esto me refiero a actualizar y refrescar el tablero para que se muestre la jugada hecha, en otras palabras, ya hacer una interfaz funcional para cuando se crea una nueva partida, la otra es que si quieren completar los menús y demás donde actualmente hay prints sobre que ahí estará la función, pero avísenme quien lo hace para tomar registro, recuerden que si necesitan algo de otra rama me lo deben notificar, esta tarea es para el viernes

**Comment by alex2201** [comment]
Hola, yo me encargo de lo del tablero. Sólo que no me queda claro cuáles son los datos que nos pasaran sobre el tablero.

**Comment by AlanKev117** [comment]
Para graficar el tablero necesitamos el archivo que contiene la información del mismo en cada modificación que se hace, si no supongo mal, lo están trabajando los de tablero así que al menos eso si es algo que necesitamos de ese módulo, yo igual quisiera trabajar en el tablero gráfico. Si te refieres a eso , ¿no? :0
