### ISSUE TITLE
Aviso Modulo Persistencía

### ISSUE THREAD

**Issue by jdominguezm1300** [norman-ipn/Ajedrez2016#24]
¡Hola a todos!

Se me asigno coordinar el modulo de persistecía, así que me comunico con ustedes para poder establecer los objetivos de nuestro modulo, y terminar los detalles faltantes.

Hasta el momento hemos añadido las siguientes funciones:

Guardar Partida.
Continuar Partida.
Coordenadas Recibidas.
Obten Hora.
Actualizar Historial.
Turno Jugador.

Considero que estas funciones logran realizar lo que solicita el modulo persistencia.

Pero con el fin de que los compañeros que no han subido alguna aportación, pueden hacerlo y tener una evaluación, sugiero  que comenten que podemos agregar y asi asignar una función a cada miembro del modulo.

**Comment by IrvingLucky27** [comment]
Pues podríamos hacer una función que salve varias partidas y que el usuario escoja cuál de ellas quiera cargar.
