### ISSUE TITLE
Importante aviso para equipo del Tablero

### ISSUE THREAD

**Issue by Emm79** [norman-ipn/Ajedrez2016#25]
Hola chavos. :)
Bueno, como saben soy el coordinador y me encargaré de ponerme de acuerdo con ustedes sobre que falta agregar a nuestro módulo, así como pequeñas modificaciones, si es el caso, con el fin de lograr que el proyecto final funcione. 

He notado que han añadido funciones importantes, aun que aún falta que añadan el cuerpo de "verificar_jaque". Le pido por favor a CubeXtreme y Drazen420, si pueden hacer tal operación en este fin de semana. Para que sea justo, la siguiente modificación que sea pedida la realizaran Edrasen y Hacker.

Por cierto, por favor asegúrense de que su código funciona, ya que para mi es difícil probarlo pues no tengo computadora y por lo tanto, no puedo depurar/compilar y comprobar el funcionamiento de las funciones. Disculpen y gracias.

No olviden que si tienen dudas pueden hablar conmigo para que yo se las comunique al profesor o a los demás módulos. Buen día.

**Comment by Drazen420** [comment]
Hola Emm79, voy a trabajar en la función aunque la subiré con una indicación que diga "función necesaria" cuando haga llamadas a función. Esto es porque para terminar la función necesitamos las funciones de verificar movimiento del equipo de piezas, pero aun no las han subido así que solo haré la función y dejara las llamadas a la función con la nota que indique. Seria todo, gracias

**Comment by CubeXtreme** [comment]
Cualquier cosa o duda que tengan pueden contar conmigo para apoyarlos.
Sobre el tema de las funciones necesarias creo que sería pertinente solicitarlas al módulo de piezas.
Mañana comentaré ese tema con algunos compañeros de dicho módulo.
Gracias y buena tarde.

**Comment by Emm79** [comment]
Hola chicos!
Bueno, no se si CubeXtreme hablo con personas designadas para el módulo "piezas", pero recuerden que, como coordinador yo soy el que debo hacerme cargo de este tipo de cuestiones, por lo tanto, yo mismo les comentaré a ellos la solicitud.
Otra cosa, confieso que no tengo mucha idea de que falta para el módulo, así que, acepto nuevas ideas. 
Buen fin de semana.

**Comment by CubeXtreme** [comment]
Hola @Emm79 
Sólo quería comentarte que ya hablé con un compañero del módulo Piezas para que empiece a trabajar en las funciones que nos hacen falta tanto a nuestro módulo como a los demás.
Sin embargo, no se publicará nada a menos que el coordinador del módulo Piezas @Alichos así lo indique
Cualquier duda no duden en contactarme.
Buen día y buen fin de semana.
Saludos

**Comment by Emm79** [comment]
Esta bien CubeXtreme, gracias.
Otra cosa, no olviden comprobar que lo que llevamos hasta ahorita compila, por favor.

Para que todos trabajemos y debido a que ninguno de los otros módulos nos ha pedido hacer algo nuevo, propongo que cada uno piense y comente una función que no tengamos y pueda mejorar la funcionalidad del tablero o el proyecto en general. 
Buen día y cualquier duda, no duden en contactarme para comentársela al profesor.
