### ISSUE TITLE
Aviso módulo de IA

### ISSUE THREAD

**Issue by ghost** [norman-ipn/Ajedrez2016#26]
Buenas noches compañeros:

Yo seré la encargada de este módulo, con el fin de que se logre el objetivo del proyecto seré la conexión con el profesor y ustedes. Si alguno tiene alguna duda puede hacérmela llegar y les responderé de la manera más rápida que esté a mi alcance.

Hay que ponernos de acuerdo, puesto que por lo que he visto en el historial no todos han tenido alguna participación y no se cuenta con un plan sobre qué se hará. Espero podernos poner en contacto para definir qué se hará en la función.

Si alguien tiene algún comentario, puede enviarlo.

Hasta luego, buenas noches.

**Comment by rash240719** [comment]
Tu contacto? No aparece tu mail en tu perfil

**Comment by norman-ipn** [comment]
Pueden generar un issue directo a su coordinador, sólo necesitan el nombre de usuario de github que aparece en el README.md del proyecto

**Comment by ghost** [comment]
Compañeros, vamos a hacer la lista de requerimientos necesarios para nuestro módulo, de esta forma podremos asignarle a cada quien una tarea. Comenzaremos con sugerencias.

1) Con ayuda de interfaz haremos un testing. 
2) Necesitamos usar todas las validaciones de movimiento para nuestros condicionales. 

Espero más sugerencias de funciones. Si necesitan ayuda de otro módulo infórmenme para solicitarlas.

**Comment by ghost** [comment]
Disculpen por lo de arriba, tuve un problema con mi navegador. Por favor comenten para saber quien está trabajando o va a trabajar en el módulo. (no me deja asignar a todo el Issue, espero que ya lo estén recibiendo. @SaidSoria )

**Comment by rash240719** [comment]
@TafnesJ  Yo trabajaré. Bueeeno, ésos no son requerimientos ;P me refería a requerimientos de software, quienes no sepan bien qué son, busquen plantillas de documentos de requerimientos y basémonos en ellas. Para redactar nuestro documento de requerimientos debemos definir los casos de uso.

**Comment by ghost** [comment]
@rash240719 Ah, entiendo. podemos hacerlo. Es necesario que nos pongamos de acuerdo para podernos poner de acuerdo todos a una misma "hora" para que decidamos entre todos y aportemos ideas. 
En otro punto necesitamos prácticamente para nuestro módulo:
1) Obtener primero la posición de las piezas antes del turno de la computadora.
2) Condicionales (hay que basarnos en algoritmos como el minmax).
3) Movimiento gráfico (cambiando las piezas de la posición deseadas a la anterior) y su impresión en tablero. Este último punto con ayuda del módulo interfaz.

La mayoría de nuestro trabajo se encuentra en el punto 2, por favor investiguen el ejemplo de algoritmo mencionado, para comenzar a asignarles un trabajo.

**Comment by Yael-Estrada** [comment]
Para la posición de las piezas al inicio del turno de la IA  necesitaremos la ayuda del módulo de tablero, Pues va a ser el tablero que se imprima al final del turno del jugador el que recibamos para iniciar la jugada

**Comment by ghost** [comment]
Correcto @Yael-Estrada necesitamos una función que nos envíe la posición anterior de las piezas, creo que es módulo persistencia y de imprimir es interfaz. @norman-ipn  ¿Son los módulos correctos?

En espera de que el maestro me responda, solicitamos las funciones.

**Comment by norman-ipn** [comment]
@TafnesJ Sólo requieren la posición de las piezas en el tablero y saber de quien es el turno, algo así como 
int responder_jugada(struct tablero *el_tablero, int turno, char *respuesta)
respuesta es donde colocan la jugada que han 'calculado' en el formato "A2A4" es decir, columna fila inicial, columna fila final.

**Comment by ghost** [comment]
@norman-ipn Gracias.
