### ISSUE TITLE
Para módulo IA

### ISSUE THREAD

**Issue by rash240719** [norman-ipn/Ajedrez2016#37]
Propongo obtengamos la lista de requerimientos. En base a ella podremos delegar cuales le tocarán a cada uno de nosotros asignados a este módulo y así codifiar las funciones necesarias. Esto permitirá tener mayor sinergia.

**Comment by norman-ipn** [comment]
Hola @TafnesJ Aquí hay una propuesta para el módulo de IA.

**Comment by ghost** [comment]
Gracias. @norman-ipn
