### ISSUE TITLE
Aviso para Módulo Piezas

### ISSUE THREAD

**Issue by atziripe** [norman-ipn/Ajedrez2016#38]
Que tal, compañeros. Al parecer nuestro coordinador está desaparecido, así que me parece bien comenzar a repartirnos las tareas entre nosotros.
Los demás módulos nos solicitan ayuda para que puedan crear la función de "Verificar jaque" y el profesor avisó que piezas.o no compila. Les parece que trabajemos en eso por ahora? 
También se solicitó que agreguemos las funciones que se habían hecho en Etapa 1 en las que se validan los movimientos de cada pieza.

**Comment by carlos-ochoa** [comment]
Claro, en el transcurso de la tarde puedo revisar algunas de las funciones para verificar movimientos y trataré de ver por qué no compila piezas.o :3

**Comment by atziripe** [comment]
Muchas gracias, yo estoy agregando las funciones que se hicieron en la etapa 1 que ya están correctas :)

**Comment by Alichos** [comment]
Hola a todos, parece ser que solo necesitamos corregir lo de piezas.o,
basicamente ya sirve todo, solo necesitamos bien hecha la funcion de
enroques, asi que dos personas podrian resolver alguna de estas dos
problematicas.
Si necesitan algo o tienen dudas, diganme.

2016-12-10 15:17 GMT-06:00 Atziri Pérez García <notifications@github.com>:

**Comment by carlos-ochoa** [comment]
¿cuál vendría siendo el problema con enroques?, para atacarlo directamente

**Comment by atziripe** [comment]
Acabo de compilarlo y todos los errores vienen de las siguientes funciones:
validar_enroque_corto_blanco
validar_enroque_corto_negro
validar_enroque_largo_blanco
validar_enroque_largo_negro

**Comment by carlos-ochoa** [comment]
Vale, yo los puedo revisar, dentro de una hora :3
Gracias :D

**Comment by carlos-ochoa** [comment]
Bueno, resulta que no compilan por hacer referencia a funciones que no están en el código, las incluiré y sha

**Comment by Alichos** [comment]
Como fueron ya incluidas las funciones con todo y codigo, podrian probar
cada movimiento para checar que no haya errores (de preferencia con los
enroques )

2016-12-10 18:52 GMT-06:00 Carlos Armando Ochoa Ginera <
notifications@github.com>:
