### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by Drazen420** [norman-ipn/Ajedrez2016#39]
Perdone volver a preguntar profesor, pero podría decirme de manera breve como regresar múltiples valores de una función. No se si era con apuntadores o solo dirección de arreglos. Espero su respuesta gracias.

**Comment by Drazen420** [comment]
De igual forma quisiera preguntarle como hacer que una función ignore omita uno de los argumentos que se le pasa, lo que pasa es que en la linea 155 hago una llamada a la función a la que solo necesito pasarle 2 argumentos pero en la cabecera de la función esta el struct que no necesito pasarlo por que es parte de tablero.h, entonces mi duda es , ¿que debo hacer para evitar el error de compilación de argumentos insuficientes?
![captura de pantalla de 2016-12-10 22-17-46](https://cloud.githubusercontent.com/assets/23269732/21078052/8396f374-bf26-11e6-9d67-83eec6a11b2b.png)

**Comment by norman-ipn** [comment]
Respecto a la función, si no requiere el parámetro sólo quítalo.
