### ISSUE TITLE
De m. IA para m. Persistencia.

### ISSUE THREAD

**Issue by ghost** [norman-ipn/Ajedrez2016#41]
Buenos días.

El módulo de IA les solicita una función donde estén guardados los movimientos anteriores del jugador antes de que siga el turno del siguiente. No sé si ya esté existente, me parece que no, por favor.

Saludos.

**Comment by jdominguezm1300** [comment]
Buenos dias.

Disculpa por responder hasta este momento, asignare la función en este momento, gracias.
Saludos.

**Comment by ghost** [comment]
Muchas gracias. Saludos.
