### ISSUE TITLE
Asigaciones Modulo Persistencia

### ISSUE THREAD

**Issue by jdominguezm1300** [norman-ipn/Ajedrez2016#42]
Hola a todos.

Las siguientes asignaciones, seran solo para aquellos que no han hecho algún "commit" a la fecha con el apoyo de quienes ya han colaborado.

**Función de que cada movimeinto que haga el jugador, se guarde en un archivo, antes del siguiente turno (Solicitada por el modulo IA)**.

Isam David Espinosa Flores 
Ivone Martínez Serrano

Asesor: Jose Armando Rivera Ramirez

**Función que le permite elegir al jugador, que partida, de las que a salvado, quiere continuar.**

Jorge Luis Mendez Alvarez
Karla Lizbeth Silva Rojas

Asesor: Irving M.Bautista Neyra.

Cualquier duda, pueden comunicarse conmigo. Yo estare colaborando con ustedes en ambas funciones. Recuerden que los commits solo los subiran aquellos que aun no han participado.

Gracias.
 
Saludos.

**Comment by JoseRivera12** [comment]
El módulo ya lo dejaremos com las funciones que tiene o cambiaremos algo

**Comment by Lalaandrea** [comment]
Joaquin Estaba checando la segunda función y las maneras que encontré de realizarlo es con c++ ammmm No se si tu tengas una idea de como realizarlo

**Comment by jdominguezm1300** [comment]
Hola Jose, me parece que se cadara con esas funciones, solo que alguno de los compañeros faltantes suba antes de las 8:00 a.m de mañana las funciones sugeridas.

**Comment by jdominguezm1300** [comment]
Hola Laura, si esta en C++ es posible pasarse a C, sin embargo yo te sugeriria que usaras las funciones que ya estan que son, cargar partida y guardar partida, y la nueva funcion, guardando cada partida en distinto archivo, y en la nueva funcion, pongas un limite de archivos, podrian ser 10, que el usuario puede generar, y de acuerdo a lo que el ingreso, cargar ese archivo.
