### ISSUE TITLE
De Persistencía a P.Norman

### ISSUE THREAD

**Issue by jdominguezm1300** [norman-ipn/Ajedrez2016#44]
Buenos dias profesor, le comento sobre la compañera Laura Andrea Morales, (LalaAndrea) que fue eliminada del repositorio, despues del recorte, ya había actualizado su perfil, sin embargo días despues no se le permitio realizar algun commit, espero su pronta respuesta.

**Comment by norman-ipn** [comment]
Hola, ya tenía la invitación enviada, pero no la había aceptado (llega a su correo), de todos modos ya generé una segunda invitación @LalaAndrea @JoaksIPN
