### ISSUE TITLE
Solicitud de asignación de tarea 

### ISSUE THREAD

**Issue by Quintaneishon** [norman-ipn/Ajedrez2016#45]
Soy del módulo tablero y solicito una tarea por parte de mi coordinador.

**Comment by norman-ipn** [comment]
Hola @HackerManchister, necesitas etiquetar a tu coordinador o asignarle este issue.
Del lado derecho donde dice "Assignees" puedes seleccionar el nombre de la personas a la que le asignas el 'issue'
