### ISSUE TITLE
Cierre de github (Ordinario)

### ISSUE THREAD

**Issue by norman-ipn** [norman-ipn/Ajedrez2016#46]
El jueves 15 de diciembre a las 8:00 a.m. se cierra el proyecto, para iniciar
la revisión y asignar calificaciones finales (Ordinarias). 
Por favor suban todo el código que se revisará 
antes de esta hora. Todo el código debe compilar y estar indentado,
cualquier falta a estas reglas queda fuera de la tercer etapa.
por favor avisen a todos los compañeros de sus respectivos módulos.

**Comment by Emm79** [comment]
Profe, en el caso de nuestro módulo (tablero), no hubo mucho que hacer, ya que nos demás no nos pidieron nada, a pesar de ello, hicimos algunas mejoras y pensamos que nuestro módulo esta terminado, para que usted lo revise debe estar en una carpeta o en otra forma diferente a como aparece en la lista de funciones, o dejamos ambas funciones (código fuente y cabecera)?
Buena noche

**Comment by norman-ipn** [comment]
Hola @Emm79 voy a revisar los archivos así como están en el repositorio. Los commits de cada uno se ven reflejados en el archivo.
