### ISSUE TITLE
Asignaciones finales para módulo tablero: CHECAR COMENTARIOS

### ISSUE THREAD

**Issue by Emm79** [norman-ipn/Ajedrez2016#47]
El profesor nos comentó que este 15 de diciembre se cierra el proyecto, por lo tanto, para un día antes (mañana, miércoles, en la noche), deberá estar terminada nuestra parte.

La verdad es que aparentemente nuestro módulo ya esta terminado; ninguno de los otros módulos nos pidió algún avance y cubrimos lo necesario de acuerdo a los requerimientos que se habían pedido con anterioridad.

Por ese motivo, no les he asignado a algunos, tareas a realizarse. Por esto, lo que deben hacer es:

- **HackerManchister**, tu encargate por favor de revisar si cada función de nuestro módulo compila (depurando), si encuentras algún error, te pido por favor que me avises (a más tardar el miércoles a las 5 pm)  para que se lo haga saber al módulo correspondiente (pues probablemente falte alguna función de estos). 
- **Edrazen y Cubextreme**, encarguense del Makefile, es decir: agregar las nuevas instrucciones que hemos hecho en el módulo, y si es posible, borren los archivos que no importen (escriban instrucciones que borren los archivos con "~", entre otros que no se requieran). Al ser 2 tareas, tienen que checar que hará cada uno . 
- **Drazen420**. tu ya tenias asignada una tarea, por favor terminala (ya que te faltaba algo de otro módulo, hasta donde recuerdo). Una vez hecho eso, modifica el "tablero.h" agregándole estos cambios y fíjate si ya esta terminado (con todas las cabeceras necesarias).

Disculpen por apurarlos, pero pues no hubo requerimientos de parte de los demás módulos y no se me ocurría que asignarles. 
Que tengan buen día y si tienen dudas, mandenme un issue y asignenme a él.

**Comment by CubeXtreme** [comment]
Hola @Emm79 
Propongo agregar las instrucciones al Makefile ya que no me es posible eliminar archivos desde terminal pues no tengo Ubuntu
uwu
Gracias y buenas tardes

**Comment by Quintaneishon** [comment]
Ya revise e indente los.archivos de tablero

**Comment by CubeXtreme** [comment]
Hola @Emm79 
Al parecer el Makefile ya tiene las instrucciones que se requieren
Debo aclarar que este archivo lo creo @norman-ipn hace dos semanas
Así que por esa parte el Makefile estaría terminado
No sé si @Edrasen nos haya hecho favor de borrar archivos "basura" como los "~"
Sería todo
Gracias y buenas tardes

**Comment by Emm79** [comment]
Les asigné la tarea y les pedí una especie de avance o mínimo duda antes de las 5, por lo visto Edrasen no ha hecho nada, por lo tanto probablemente no lo evalúe con un trabajo completo, por lo que comentaste **Cube Xtreme** y debido a que **Hacker** ya terminó su asignación, ahora le toca a él eliminar la basura del makefile. 
Por favor **Drazen420**, fijate si todo está indentado (tablero.c , tablero.h y nuestra parte del makefile), si falta algo por indentar, por favor hazlo. 
**CubeXtreme**, por último a  ti te pido, te fijes que todos los nombres de funciones llamadas de los otros módulos son los correctos, si ves uno mal, por favor cambialo (ya que por lo visto Norman encontró un error en un nombre).
Hecho esto, avisenme comentando en este issue, para que le diga a Norman que ya terminamos la función. Buen día.

**Comment by CubeXtreme** [comment]
Ya quedó
El problema con la funcion era que se llamaba capturar_caracter();
Después de eso hay algunos errores más de compilación
La mayoría warnings
![image](https://cloud.githubusercontent.com/assets/23238911/21206353/0b6c5bc4-c227-11e6-9f10-eaa93137f755.png)

**Comment by CubeXtreme** [comment]
Hola @Emm79 
Básicamente de nuestro módulo no hay quejas del compilador
Así que prácticamente estaría acabado nuestro módulo
Gracias
Buenas Tardes

**Comment by Edrasen** [comment]
Hola, lamento no haber realizado la tarea pero no entendi a que se referian a los archivos basura, al parecer ya esta todo hecho y entiendo que no me tomes la evaluación completa, una disculpa a todos.
Buenas noches.

**Comment by Edrasen** [comment]
A que se refieren con limpiar la basura del Makefile?
No entiendo esa parte

**Comment by Emm79** [comment]
Era borrar archivos que se crean al hacer pruebas de depuración, tales como los que terminan en "~" y los ".o".
Mira Edrasen, aun hay algo que no se ha checado, y es que todas las funciones que nosotros creamos (en tablero.c y .h) deben estar en infinitivo, checalo y cambialo por favor, si es el caso. 
De acuerdo contigo Cube Xtreme. Ya solo falta lo que dije anteriormente. 
Le diré a Norman que si dejamos como tal las funciones o si las metemos a un documento o algo así y les aviso en estos comentarios hoy mismo, OK?
Buenas noches

**Comment by Edrasen** [comment]
Me percate de que la parte de los colores aún aparece en el archivo "tablero.h", sin embargo en el archivo "tablero.c" las funciones de los colores fueron marcadas como comentarios al final del archivo, entonces ¿debo borrar la parte de los colores del archivo .h?

**Comment by CubeXtreme** [comment]
@Edrasen , @Emm79 
También yo tengo duda en esa parte
Qué se debe hacer con esa parte del código?
La eliminamos de ambos o las dejamos en ambos?

**Comment by Emm79** [comment]
Si ven que ningún modulo las utiliza,  si necesito que las borren de ambos archivos.

**Comment by Emm79** [comment]
Para esas funciones hay un problema con el modulo interfaz: supuestamente uno de los integrantes de ese módulo le indicó a uno de ustedes que debía hacerse esas funciones (forma incorrecta de resolver el problema, ya que su coordinador jamás se puso en contacto conmigo). 
Entonces, yo le voy a mandar mensaje a su coordinador pars llegar a un acuerdo, la verdad yo no le veo mucho caso a esas funciones, probablemente se terminaran borrando de ambos módulos.
