### ISSUE TITLE
Entrega de módulo Inteligencia Artificial

### ISSUE THREAD

**Issue by ghost** [norman-ipn/Ajedrez2016#48]
Buenas noches compañeros, el profesor Norman anunción que el proyecto se cerrará el día ueves 15 de Diciembre (a las 8:00 a.m.), por lo cual sus funciones deben estar listas para el día de mañana, de esta forma podremos verificar que compilen y que estén correctas, todos tienen una tarea asignada, si tienen alguna opinión, preguntas, etc no duden en hacérmela llegar.

**Comment by SoyOscarRH** [comment]
En mi caso no se me ha asignado ninguna tarea, ¿Como le puedo ayudar mañana?

**Comment by ghost** [comment]
Te asigné los condicionales de peones. Podrías ayudarnos a verificar que los encabezados estén correctos en IA.h :)

**Comment by ghost** [comment]
Ya revisé los cambios que has hecho, de hecho sólo hay que poner los condicionales y modificar el rand, estaré trabajando en eso. @SoyOscarRH
