### ISSUE TITLE
Finalización de proyecto

### ISSUE THREAD

**Issue by mauricioww** [norman-ipn/Ajedrez2016#49]
Buenas noches compañeros, el profesor Norman anunción que el proyecto se cerrará el día ueves 15 de Diciembre (a las 8:00 a.m.), por lo cual sus funciones deben estar listas para el día de mañana, de esta forma podremos verificar que compilen y que estén correctas.

Recuerden que el proyecto va a ser la forma de evaluacion.

**Comment by LuisVitax** [comment]
Hola compañero , oye yo subí un chat entre usuario y jugador antes del
juego  a red , solo que no he probado si compile , en mi compu si lo hizo

**Comment by leafar5645** [comment]
red.c no compila por la funcion main_servidor2 , yo subi un funcion cliente para el chat y si compila, el problema es solo main_servidor2

**Comment by MartinBarriga** [comment]
Me puse a revisar cuál era el problema de "main_serivodr2" y vi que tenía el mismo nombre que otra función de abajo, por lo que le quité el 2 sin problemas ya que no había ninguna otra función que lo mandara llamar. Sin embargo, "main_servidor" (anteriormente main_servidor2) manda llamar una función pero le manda variables que no han sido declaradas, eso no lo corregí porque no sé en cuánto se deban de inicializar. 
Otra cosa, me parece que todavía nos hace falta agregar una función que se encargue de que cuando un jugador hace un movimiento inmediatamente le llegue al jugador 2 y viceversa.

**Comment by LuisVitax** [comment]
Hola ,oye estuve checando el código y trate como de arreglarlo pero me
marcaba error en una función main , la moví pero no pude hacer que
compilara , esto lo hice en mi compu no en el repositorio , y me dijo
norman que tu asignarlas caliicaciones
