### ISSUE TITLE
Envío de calificaciones ETAPA 3

### ISSUE THREAD

**Issue by norman-ipn** [norman-ipn/Ajedrez2016#52]
Hola a todos los coordinadores, por favor manden la lista de calificaciones de las personas que participaron en su módulo. Si alguno de los compañeros les pide su calificación por favor háganselas saber.
Gracias a todos por su participación :D 

NOTA: por favor cierren todos los issues que tengan pendientes de cerrar.

**Comment by ghost** [comment]
Calificaciones del módulo IA enviadas. @norman-ipn

**Comment by Emm79** [comment]
Yo le recuerdo que ya se las envíe por correo (maya.rocha.emmanuel).
Buen día.

**Comment by jdominguezm1300** [comment]
Calificaciones del módulo Persistencia enviadas, a su correo @norman-ipn Saludos.

**Comment by mauricioww** [comment]
Calificaciones del módulo de RED enviadas a su correo. Salidos     =)
