### ISSUE TITLE
IA

### ISSUE THREAD

**Issue by SaulFloresCortes** [norman-ipn/Ajedrez2016#55]
Buenas días profesor, @Leonelney  @JorgeMendezcm1  y yo queremos trabajar en la IA pero tenemos una idea distinta de lo que hay actualmente en el modulo ¿Habría algún problema si lo modificamos por completo o tenemos que trabajar a partir de lo que ya hay?

**Comment by norman-ipn** [comment]
Trabajen en la idea base que es: 
Entrada: un tablero y un turno
Salida: una jugada
No borren funciones, sólo incluyan las suyas.
