### ISSUE TITLE
Tengo conflictos con red.c

### ISSUE THREAD

**Issue by kikerique** [norman-ipn/Ajedrez2016#56]
corregí los problemas de compilacion de red.c excepto los que tienen que ver con la llave que creo hace falta y algo de las funciones write, pero tu commit  @WholeCharlygold ya no me deja hacer push :(

**Comment by WholeCharlygold** [comment]
Solamente haz un push forzado y ya. Solo arregle un problema de parentesis en un "if".

**Comment by kikerique** [comment]
pues se subieron muchos commits raros pero al parecer los errores que corregí ya están, solo falta una llave que cierra creo
