### ISSUE TITLE
a.out en repositorio

### ISSUE THREAD

**Issue by arturock127** [norman-ipn/Ajedrez2016#59]
Según recuerdo, el profe @norman-ipn nos dijo que el a.out no debía subirse nunca. @norman-ipn le pregunto si tengo derecho de borrarlo.

**Comment by kikerique** [comment]
si es así borralo, desconocía eso

**Comment by ghost** [comment]
Pregunta .  Los *.o no se supone que tampoco tienen que estar

**Comment by CubeXtreme** [comment]
Se supone que no
No recuerdo bien que comentó el profe @norman-ipn al respecto
Sin embargo se me hace raro que estén aquí en el repositorio
También hay un archivo  *.c~
Esos se tienen que borrar según yo
Profe @norman-ipn  tengo derecho a borrarlo?

**Comment by norman-ipn** [comment]
ya reporté este archivo, pero si pueden borrarlo, no deben estar en el repositorio

**Comment by norman-ipn** [comment]
Achivos ejecutables. a.out, bibliotecas precompiladas .o y temporales .c~ .h~ no deben estar en el repositorio.
